apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svc2-service
  name: svc2-service
spec:
  selector:
    matchLabels:
      app: svc2-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: svc2-service
        ssd.admissionreview.accountname: production
        ssd.admissionreview.appname: svc2-service
    spec:
      containers:
      - name: svc2-service
        image: opsmx11/spring-service-production:1b4e55a-16
